### ISSUE TITLE
url broken in README.md

### ISSUE THREAD

**Issue by martin-flower** [aws-samples/aws-cognito-java-desktop-app#7]
The read me file contains a url which returns 404.

**Comment by koiker** [comment]
Sorry for the inconvenience.
I've fixed the url.

**Comment by sbmaggarwal** [comment]
@koiker This is still broken I think. Not reachable: https://sid343.reinvent-workshop.com/

**Comment by praetp** [comment]
The URL is still not reachable.
